account/urls.py
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name = 'register'),
    path('login/', views.login, name = 'login'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('add/<int:shop_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:shop_id>/', views.cart_remove, name = 'cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from shop import views

from django.conf.urls.static import static
from django.conf import settings


app_name = "shop"

urlpatterns = [
    path('admin/', admin.site.urls),
#   path('shop/', views.index),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path('', views.index, name='list'),
#   path('shop/', views.index, name='list'),
    path('<int:shop_id>/', views.detail, name='detail'),    
]


account/models.py
from django.db import models

# Create your models here.
class Member(models.Model) :
    name = models.CharField(max_length=20)
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=50)
    email = models.EmailField(max_length=128)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'member'
        verbose_name_plural = "members"

    def __str__(self):
        return self.username

cart/models.py
from django.db import models
from shop.models import Shop


# Create your models here.
class Cart(models.Model) :
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta :
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self) :
        return self.cart_id

class CartItem(models.Model) :
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default = True)

    class Meta :
        db_table = 'CartItem'

    def sub_total(self) :
        return self.shop.price * self.quantity
    
    def __str__(self) :
        return self.shop

shop/models.py
from django.db import models

# Create your models here.
#카테고리
#사진
#상품명
#가격
#설명

class Shop(models.Model) :
    category = models.CharField(max_length=10, default='')
    image = models.ImageField(upload_to='image/')
    name = models.CharField(max_length=50)
    price = models.IntegerField(default=0)
    content = models.TextField()







account/forms.py
from django import forms
from .models import Member
from django.contrib.auth.hashers import check_password

class LoginForm(forms.Form):
    username = forms.CharField(error_messages={
        'required':'아이디를 입력하세요!'
    },max_length=100, label="Username")
    password = forms.CharField(error_messages={
        'required':'비밀번호를 입력하세요!'
    },widget=forms.PasswordInput, max_length=100, label="Password")
    
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            try:
                member = Member.objects.get(username=username)
            except Member.DoesNotExist:
                self.add_error('username', '아이디가 없습니다!')
                return

        if not check_password(password, member.password):
            self.add_error('password', '비밀번호가 다릅니다!')
        else:
            self.user_id = member.id

account/views.py

from django.shortcuts import render, redirect
from django.contrib.auth.hashers import make_password

from .models import Member
from .forms import LoginForm

# Create your views here.
def register(request):
    if request.method == "GET":
        return render(request, 'register.html')

    elif request.method == "POST":
        name = request.POST.get('name', None)
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        re_password = request.POST.get('re_password', None)
        email = request.POST.get('email', None)

        res_data = {}
        if not (name and username and password and re_password and email):
            res_data['error'] = 'Please enter all the values!'

        elif password != re_password:
            res_data['error'] = "The password doesn't match!"
            print(res_data)

        else:
            member = Member (
                name = name,
                username = username,
                email = email,
                password = make_password(password),
            )
            member.save()
            return redirect('/shop')

        return render(request, 'register.html', res_data)

def login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            # session_code 검증하기
            request.session['user'] = form.user_id
            return redirect('/shop')
    else:
        form = LoginForm()
    
    return render(request, 'login.html', {'form': form})

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from cart.models import Cart, CartItem
from shop.models import Shop

# Create your views here.
def _cart_id(request) :
    cart = request.session.session_key
    if not cart :
        cart = request.session.create()
    return cart

def add_cart(request, shop_id) :
    shop = Shop.objects.get(id=shop_id)
    try :
        cart = Cart.objects.get(cart_id = _cart_id(request))
    except Cart.DoesNotExist :
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
        cart.save()

    try :
        cart_item = CartItem.objects.get(shop = shop, cart = cart)
        cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist :
        cart_item = CartItem.objects.create(
            shop = shop,
            quantity = 1,
            cart = cart
        )
        cart_item.save()
    
    return redirect('cart:cart_detail')

def cart_detail(request, total = 0, counter = 0, cart_items = None) :
    try :
        cart = Cart.objects.get(cart_id = _cart_id(request))
        cart_items = CartItem.objects.filter(cart = cart, active = True)
        for cart_item in cart_items :
            total += (cart_item.shop.price * cart_item.quantity)
            counter += cart_item.quantity
    except Cart.DoesNotExist :
        pass
    except CartItem.DoesNotExist :
        pass 

    return render(request, 'cart.html', dict(cart_items = cart_items, total=total, counter=counter))

def cart_remove(request, shop_id) :
    cart = Cart.objects.get(cart_id = _cart_id(request))
    shop = get_object_or_404(Shop, id = shop_id)
    cart_item = CartItem.objects.get(shop = shop, cart = cart)

    if cart_item.quantity > 1 :
        cart_item.quantity -= 1
        cart_item.save()
    else :
        cart_item.delete()
    
    return redirect('cart:cart_detail')


shop/views.py
from django.shortcuts import render
#from django.http import HttpResponse
from .models import Shop
# Create your views here.

def index(request) :
    shop_list = Shop.objects.all
    context = {'shop_list' : shop_list}
 #  return HttpResponse("Shop index page.")
    return render(request, 'shop_list.html', context)

def detail(request, shop_id):
  shop = Shop.objects.get(id=shop_id)
  context = {'shop': shop}
  return render(request, 'shop_detail.html', context)

templates/cart.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
{% extends "shop_detail.html" %}
{% load humanize %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shop:list' %}">&nbsp;&nbsp;&nbsp;LJM</a>    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
<div class="collapse navbar-collapse flse-grow-0" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item ">                                                                
            <li><a class="nav-link" href="#">&nbsp;&nbsp;OUTER</a></li>
            <li><a class="nav-link" href="#">&nbsp;TOP</a></li>
            <li><a class="nav-link" href="#">&nbsp;BOTTOM</a></li>               
        </li> 
    </ul>
</div>
<div class = "left-side" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item ">                                                                
            <a class="nav-link" href="">CART</a>
            <a class="nav-link" href="{% url 'account:login' %}">Sign In</a>
            <a class="nav-link" href="{% url 'account:register' %}">Sign Up</a>            
        </li>
    </ul>
</div>
</nav>
    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    Your shopping cart is empty.
                </h1>
                <br>
                <p class="text-center">
                    Please click <a href="{% url 'shop:list' shop.id%}">here</a> to continue shopping.
                </p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    CART
                </h1>
                <br>
            </div>
        </div>
        <div  class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thread class="my_custom_thread">
                        <tr>
                            <th colspan="5">
                                Your items
                            </th>
                        </tr>
                    </thread>
                    <tbody>
                    {% for cart_item in cart_items %}
                        <tr>
                            <td>
                                <a href="{{cart_item.shop.get_url}}"><img src="{{cart_item.shop.image.url}}" alt="" class="float-left rounded custom_image"></a>
                            </td>
                            <td class="text-center">
                                <br>
                                <br>
                                <br>
                                <br>
                                {{cart_item.shop.name}}
                                <br>
                                <br>
                                price : {{cart_item.shop.price}}
                                <br>
                                <br>
                                <br>
                                Qty : {{cart_item.quantity}} X {{cart_item.shop.price}}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="text my_custom_table">
                    <thread class="my_custom_thread">
                        <tr>
                            <th colspan="5">
                                <br>
                                Checkout
                                <br>
                                <br>
                                <br>
                            </th>
                        </tr>
                    </thread>
                    <tbody>                     
                        <tr>
                            <td class="text-center">
                                Your total is : <strong>{{total}}</strong>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center">
                                <br>
                                <br>
                                <a href="{% url 'shop:list' %}" class="btn btn-secondary btn-block my_custom_button">Order now</a>
                            </td>
                        </tr>
                    </tbody>
                </table>                                
            </div>
        </div>
    </div>     
        {% endif %}
{% endblock %}

templates/login.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
{% load humanize %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shop:list' %}">&nbsp;&nbsp;&nbsp;LJM</a>    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
<div class="collapse navbar-collapse flse-grow-0" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item ">                                                                
            <li><a class="nav-link" href="#">&nbsp;&nbsp;OUTER</a></li>
            <li><a class="nav-link" href="#">&nbsp;TOP</a></li>
            <li><a class="nav-link" href="#">&nbsp;BOTTOM</a></li>               
        </li> 
    </ul>
</div>
<div class = "left-side" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item ">                                                                
            <a class="nav-link" href="">CART</a>
            <a class="nav-link" href="{% url 'account:login' %}">Sign In</a>
            <a class="nav-link" href="{% url 'account:register' %}">Sign Up</a>            
        </li>
    </ul>
</div>
</nav>

<div class="container">
    <div class="row mt-5">
        <div class="col-12 text-center">
            <h1>Sign In</h1>
        </div>
    </div>
</div>
  
<div class="container">
    <div class="row mt-5"></div>
        <div class="col-12">
            {{error}}
        </div>
        <br>
        <div class="col-12">
            <form method = "POST" action=".">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    <input
                      type="{{ field.field.widget.input_type }}"
                      class="form-control"
                      id="{{ field.id_for_label }}"
                      placeholder="{{ field.label }}"
                      name="{{ field.name }}"
                      style="width:50%"
                    />
                </div>
                {% if field.errors %}
                <span style="color: red;">{{ field.errors }}</span>
                {% endif %} 
                {% endfor %}
                <br>
                <button type="submit" class="btn btn-secondary btn-block my_custom_button"  style="width:50%" href="#">Sign In</button>
                <br>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/register.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
{% load humanize %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shop:list' %}">&nbsp;&nbsp;&nbsp;LJM</a>    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
<div class="collapse navbar-collapse flse-grow-0" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item ">                                                                
            <li><a class="nav-link" href="#">&nbsp;&nbsp;OUTER</a></li>
            <li><a class="nav-link" href="#">&nbsp;TOP</a></li>
            <li><a class="nav-link" href="#">&nbsp;BOTTOM</a></li>               
        </li> 
    </ul>
</div>
<div class = "left-side" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item ">                                                                
            <a class="nav-link" href="">CART</a>
            <a class="nav-link" href="{% url 'account:login' %}">Sign In</a>
            <a class="nav-link" href="{% url 'account:register' %}">Sign Up</a>         
        </li>
    </ul>
</div>
</nav>

<div class="container">
    <div class="row mt-5">
        <div class="col-12 text-center">
            <h1>Sign Up</h1>
            <small id="emailHelp" class="form-text text-muted">We'll never share your info with anyone else.</small>
        </div>
    </div>
</div>
  
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            {{error}}
        </div>
        <br>
        <div class="col-18">
            <form method = "POST" action=".">
                {% csrf_token %}
                <div class="form-group text-left">
                    <label for="name">Name</label>
                    <input type="text" class="form-control btn-block" id="name" placeholder="name" name="name" style="width:50%" >
                </div>
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control btn-block" id="username" placeholder="username" name="username" style="width:50%">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control btn-block" id="password" placeholder="password" name="password" style="width:50%">
                </div>
                <div class="form-group">
                    <label for="re_password">Re_Password</label>
                    <input type="password" class="form-control btn-block" id="re_password" placeholder="re_password" name="re_password" style="width:50%">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control btn-block" id="email" placeholder="email" name="email" style="width:50%">
                </div>
                <button type="submit" class="btn btn-secondary btn-block my_custom_button"  style="width:50%" >Sign Up</button>
                <br>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/shop_detail.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
{% load humanize %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shop:list' %}">&nbsp;&nbsp;&nbsp;LJM</a>    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flse-grow-0" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item ">                                                                
            <li><a class="nav-link" href="#">&nbsp;&nbsp;OUTER</a></li>
            <li><a class="nav-link" href="#">&nbsp;TOP</a></li>
            <li><a class="nav-link" href="#">&nbsp;BOTTOM</a></li>               
        </li> 
    </ul>
</div>
<div class = "left-side" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item ">                                                                
            <a class="nav-link" href="{%url 'cart:add_cart' shop.id%}">CART</a>
            <a class="nav-link" href="{% url 'account:login' %}">Sign In</a>
            <a class="nav-link" href="{% url 'account:register' %}">Sign Up</a>             
        </li>
    </ul>
</div>
</nav>
<div class="container">
    <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg6 text-center">
                <div style="min-width: 6rem">
                    <p class="text-justify my_prod_text">{{shop.category}}</p>
                    <img src = "{{shop.image.url}}" alt = "{{shop.name}}">
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-right">
                <div>
                    <h1 class="my_prod_title">{{shop.name}}</h1>
                    <h2>{{shop.price|intcomma}}</h2>
                    <br>
                    <p class="text-justify my_prod_text">detail...</p>
                    <p class="text-justify my_prod_text">{{shop.content}}</p>
                    <a class="btn btn-secondary" href = "{% url 'cart:add_cart' shop.id%}">Add to Cart</a>
                </div>
            </div>
        </div>
</div>
{% endblock %}

templates/shop_list.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
{% load humanize %}
{% block contents %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shop:list' %}">&nbsp;&nbsp;&nbsp;LJM</a>    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flse-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">                                                            
                <li><a class="nav-link" href="#">&nbsp;&nbsp;OUTER</a></li>
                <li><a class="nav-link" href="#"&nbsp;>TOP</a></li>
                <li><a class="nav-link" href="#">&nbsp;BOTTOM</a></li>
            </li>
        </ul>
    </div>
    <div class = "left-side" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">                                                                
                <a class="nav-link" href="#">CART</a>
                <a class="nav-link" href="{% url 'account:login' %}">Sign In</a>
                <a class="nav-link" href="{% url 'account:register' %}">Sign Up</a>             
            </li>
        </ul>
    </div>
</nav>
    <div class="row">
        {% for shop in shop_list %}
        <div class="col-sm-4">
            <div class="card mb-3">
                <div class="embed-responsive embed-responsive-4by3">
                    <img class="card-img-top embed-responsive-item" src="{{ shop.image.url }}" width="100" />
                </div>
                <div class="card-body">
                    <h3 class="card-title h4">{{ shop.name }}</h3>
                    <a class="btn btn-secondary" href="{% url 'shop:detail' shop.id %}">detail</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}